development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: bot-tracker_production


REDISTOGO_URL


# config/cable.yml

production:
  adapter: redis
  url: <%= ENV['REDISTOGO_URL'] %>


development:
  adapter: async

test:
  adapter: async
